[package]
name = "mail-helper-legacy"
version = "0.3.12"
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
mail-decoder-legacy = { path = "../mail-decoder-legacy" }
