[package]
name = "mail-processor"
version = "0.3.1"
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
itoa = { workspace = true }