[package]
name = "mail-decoder-v2"
# This version differs from the rest of our codebase because this is a prerelease prior to data migration.
version = "0.4.0"
edition = "2024"

[dependencies]
serde_json = { workspace = true }