[workspace]
members = [
    "crates/mail-cli",
    "crates/mail-decoder",
    "crates/mail-processor",
    "crates/mail-helper",
    "crates/rokbattles-api",
    "crates/rokbattles-processor",
    "crates/rokbattles-tauri/src-tauri"
]
resolver = "3"

[workspace.dependencies]
anyhow = "1.0.100"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
clap = { version = "4.5.49", features = ["derive"] }
itoa = "1.0.15"
axum = "0.8.6"
tokio = { version = "1.47.1", features = ["full"] }
tower-http = { version = "0.6.6", features = ["fs", "trace", "limit", "timeout"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
tikv-jemallocator = "0.6.0"
tauri-build = { version = "2.4.1", features = [] }
tauri = { version = "2.9.5", features = [] }
tauri-plugin-opener = "2.5.2"
tauri-plugin-dialog = "2.4.2"
futures-util = "0.3.31"
mongodb = "3.3.0"
zstd = "0.13.3"
blake3 = "1.8.2"
reqwest = "0.12.24"
futures = "0.3.31"
tauri-plugin-updater = "2.9.0"
