[workspace]
members = [
    "crates/mail-decoder",
]
resolver = "3"

[workspace.dependencies]
serde_json = "1.0.149"

[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"