[workspace]
members = [
    "crates/mail-cli",
    "crates/mail-decoder",
    "crates/mail-processor",
    "crates/mail-processor-sdk",
    "crates/mail-processor-duelbattle2",
    "crates/mail-helper",
    "crates/rokbattles-api",
    "crates/rokbattles-processor",
    "crates/rokbattles-tauri/src-tauri"
]
resolver = "3"

[workspace.dependencies]
anyhow = "1.0.100"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
clap = { version = "4.5.53", features = ["derive"] }
itoa = "1.0.15"
axum = "0.8.7"
tokio = { version = "1.48.0", features = ["full"] }
tower-http = { version = "0.6.8", features = ["fs", "trace", "limit", "timeout"] }
tracing = "0.1.43"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
tikv-jemallocator = "0.6.1"
tauri-build = { version = "2.5.3", features = [] }
tauri = { version = "2.9.5", features = [] }
tauri-plugin-opener = "2.5.2"
tauri-plugin-dialog = "2.4.2"
futures-util = "0.3.31"
mongodb = "3.4.1"
zstd = "0.13.3"
blake3 = "1.8.2"
reqwest = "0.12.26"
futures = "0.3.31"
tauri-plugin-updater = "2.9.0"
memchr = "2.7.6"
notify = "8.2.0"
