spring:
  application:
    name: rokbattles
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: ${DISCORD_CLIENT_ID}
            client-secret: ${DISCORD_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: "{baseUrl}/api/oauth2/callback/{registrationId}"
            scope:
              - identify
              - email
            provider: discord
        provider:
          discord:
            authorization-uri: https://discord.com/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: id

app:
  frontend-url: ${APP_FRONTEND_URL:http://localhost:8080}
