[package]
name = "mail-processor-duelbattle2"
version = "0.3.4"
edition = "2024"

[dependencies]
mail-processor-sdk = { path = "../mail-processor-sdk" }
serde = { workspace = true }
serde_json = { workspace = true }
