[package]
name = "binidx-cli"
version = "1.0.0-rc.2"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
binidx-decoder = { path = "../binidx-decoder" }
