[package]
name = "mail-processor-battle-legacy"
version = "0.3.12"
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
itoa = { workspace = true }
mail-processor-sdk-legacy = { path = "../mail-processor-sdk-legacy" }
