[package]
name = "rokbattles-processor"
version = "0.3.5"
edition = "2024"

[dependencies]
tokio = { workspace = true }
mongodb = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
zstd = { workspace = true }
mail-processor = { path = "../mail-processor" }
futures = { workspace = true }
blake3 = { workspace = true }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { workspace = true }